apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-project
  labels:
    app: netflix-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-project
  template:
    metadata:
      labels:
        app: netflix-project
    spec:
      containers:
      - name: netflix-app
        image: owaisrizvi97/netflix-project:latest
        ports:
        - containerPort: 80
