apiVersion: v1
kind: Service
metadata:
  name: netflix-project
  labels:
    app: netflix-project
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
  selector:
    app: netflix-project
